# This is a basic workflow to help you get started with Actions

name: Code Style

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "check-format"
  check-format:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.5.0
      with:
        # SDK version to use. Examples: 2.2.104, 3.1, 3.1.x
        dotnet-version: 3.1.x
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
      with:
        # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
        node-version: 14.x
    - name: Restore .NET Core dependencies
      run: |
        dotnet restore
        dotnet tool restore
    - name: Install Node.js dependencies
      uses: bahmutov/npm-install@v1
      with:
          working-directory: ClientApp
    - name: Check code style
      run: |
        dotnet format --check
        (cd ClientApp && npm run lint)
